/* Auto-generated by build-recipes.mjs — 100 items. Run: node build-recipes.mjs */
window.MFP_RECIPES = [
  {
    "category": "breakfast",
    "title": "Overnight oats (classic)",
    "ingredients": [
      "Rolled oats 50 g",
      "Semi-skimmed milk 150 ml",
      "Greek or low-fat yoghurt 80 g",
      "Chia seeds 1 tsp",
      "Berries or chopped apple",
      "Optional: 1 tsp honey"
    ],
    "kcal": "~320",
    "protein": "~14",
    "note": "Mix night before; eat cold.",
    "source": "https://www.bbcgoodfood.com/recipes/collection/overnight-oats-recipes",
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Masala savoury oats",
    "ingredients": [
      "Rolled oats 45 g",
      "Water 200 ml",
      "Onion ¼ chopped",
      "Tomato ½ chopped",
      "Green chilli 1",
      "Turmeric ¼ tsp",
      "Cumin seeds ½ tsp",
      "Oil 1 tsp",
      "Salt",
      "Coriander to garnish"
    ],
    "kcal": "~280",
    "protein": "~9",
    "note": "Cook like savoury porridge; desi twist.",
    "source": null,
    "fromData": "Inspired by common masala oats patterns"
  },
  {
    "category": "breakfast",
    "title": "Egg bhurji + 1 roti",
    "ingredients": [
      "Eggs 2",
      "Onion, tomato, green chilli",
      "Turmeric pinch",
      "Oil 1 tsp",
      "Wholemeal roti 1 medium"
    ],
    "kcal": "~340",
    "protein": "~22",
    "note": "High protein desi breakfast.",
    "source": null,
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Boiled eggs + fruit",
    "ingredients": [
      "Eggs 2 boiled",
      "Apple or orange 1"
    ],
    "kcal": "~220",
    "protein": "~18",
    "note": "Quick uni morning.",
    "source": null,
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Moong dal cheela",
    "ingredients": [
      "Soaked moong dal paste 80 g raw wt",
      "Onion + ginger + chilli",
      "Oil spray or 1 tsp oil",
      "Mint chutney 1 tbsp portion"
    ],
    "kcal": "~260",
    "protein": "~16",
    "note": "Griddle like thin pancake.",
    "source": null,
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Besan chilla",
    "ingredients": [
      "Besan 40 g",
      "Water to batter",
      "Onion, tomato, coriander",
      "Turmeric pinch",
      "Oil 1 tsp"
    ],
    "kcal": "~240",
    "protein": "~12",
    "note": "Chickpea flour omelette style.",
    "source": null,
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Dalia (broken wheat) porridge",
    "ingredients": [
      "Dalia 40 g dry",
      "Milk + water 250 ml",
      "Cardamom pinch",
      "Sweetener or ½ tsp honey"
    ],
    "kcal": "~280",
    "protein": "~9",
    "note": "Fiber-rich warm bowl.",
    "source": null,
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Banana peanut butter roti roll",
    "ingredients": [
      "Wholemeal roti 1",
      "Peanut butter 1 tbsp",
      "Banana ½ sliced"
    ],
    "kcal": "~320",
    "protein": "~12",
    "note": "Portable; watch pb portion.",
    "source": null,
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Low-fat yoghurt + granola small",
    "ingredients": [
      "Plain yoghurt 180 g",
      "Low-sugar granola 25 g",
      "Cinnamon pinch"
    ],
    "kcal": "~280",
    "protein": "~15",
    "note": "Pre-portion granola.",
    "source": null,
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Vegetable omelette",
    "ingredients": [
      "Eggs 2",
      "Spinach, peppers ½ cup",
      "Oil 1 tsp",
      "Feta 15 g optional"
    ],
    "kcal": "~280",
    "protein": "~20",
    "note": "Fold veg into eggs.",
    "source": null,
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Chana chaat (breakfast bowl)",
    "ingredients": [
      "Boiled kabuli chana 120 g",
      "Onion, tomato, cucumber",
      "Lemon, chaat masala pinch",
      "Green chilli"
    ],
    "kcal": "~320",
    "protein": "~18",
    "note": "Meal-prep chana on Sunday.",
    "source": null,
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Suji upma (light)",
    "ingredients": [
      "Rava 35 g dry",
      "Mustard seeds pinch",
      "Curry leaves if available",
      "Peas + carrot ½ cup",
      "Oil 1 tsp"
    ],
    "kcal": "~250",
    "protein": "~7",
    "note": "South Indian style; keep oil low.",
    "source": null,
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Paneer bhurji (light)",
    "ingredients": [
      "Crumble paneer 80 g",
      "Tomato onion masala",
      "Turmeric, chilli",
      "Oil 1 tsp"
    ],
    "kcal": "~300",
    "protein": "~22",
    "note": "Saute until dry.",
    "source": null,
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Avocado toast (1 slice)",
    "ingredients": [
      "Wholegrain bread 1 slice",
      "Avocado 35 g mash",
      "Lemon, chilli flakes",
      "Boiled egg 1 optional side"
    ],
    "kcal": "~260",
    "protein": "~14",
    "note": "Optional egg boosts protein.",
    "source": "https://www.nhs.uk/live-well/eat-well/how-to-eat-a-balanced-diet/eatwell-guide/",
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Oats smoothie",
    "ingredients": [
      "Oats 30 g",
      "Banana ½",
      "Milk 200 ml",
      "Cinnamon",
      "Ice optional"
    ],
    "kcal": "~280",
    "protein": "~10",
    "note": "Blitz until smooth.",
    "source": null,
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Roti + leftover masala chicken",
    "ingredients": [
      "Roti 1",
      "Chicken curry 100 g lean pieces",
      "Cucumber sticks"
    ],
    "kcal": "~380",
    "protein": "~35",
    "note": "Use batch chicken.",
    "source": null,
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Greek yoghurt parfait",
    "ingredients": [
      "Yoghurt 150 g",
      "Berries 80 g",
      "Flaked almonds 8",
      "Honey ½ tsp"
    ],
    "kcal": "~240",
    "protein": "~16",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Stuffed roti (gobi light)",
    "ingredients": [
      "Grated cauliflower ½ cup cooked dry",
      "Spices dry",
      "Roti 1",
      "Oil 1 tsp total"
    ],
    "kcal": "~300",
    "protein": "~10",
    "note": "Cook filling without extra oil.",
    "source": null,
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Masala scrambled tofu",
    "ingredients": [
      "Firm tofu 120 g crumbled",
      "Onion tomato",
      "Turmeric, cumin",
      "Oil 1 tsp"
    ],
    "kcal": "~240",
    "protein": "~18",
    "note": "Vegan high protein.",
    "source": null,
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Egg sandwich (brown bread)",
    "ingredients": [
      "Bread 2 slices",
      "Eggs 1–2 sliced or mayo-free",
      "Lettuce, tomato"
    ],
    "kcal": "~300",
    "protein": "~18",
    "note": "Skip mayo; use mustard if needed.",
    "source": null,
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Rice flakes (poha) light",
    "ingredients": [
      "Poha 40 g",
      "Onion, peas",
      "Turmeric, lemon",
      "Oil 1 tsp",
      "Roasted peanuts 5 g"
    ],
    "kcal": "~270",
    "protein": "~8",
    "note": "Rinse poha briefly.",
    "source": null,
    "fromData": null
  },
  {
    "category": "breakfast",
    "title": "Cottage cheese + fruit plate",
    "ingredients": [
      "Low-fat cottage cheese 120 g",
      "Melon or papaya 150 g",
      "Black pepper"
    ],
    "kcal": "~220",
    "protein": "~24",
    "note": "Fast plate.",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Chicken rice bowl (batch)",
    "ingredients": [
      "Chicken 100 g cooked",
      "Basmati rice 120 g cooked",
      "Cucumber raita 80 g"
    ],
    "kcal": "~440",
    "protein": "~35",
    "note": "Your plan staple.",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Masoor daal + roti",
    "ingredients": [
      "Masoor daal 1 cup cooked",
      "Roti 1",
      "Salad"
    ],
    "kcal": "~380",
    "protein": "~22",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Chana daal + sabzi + roti",
    "ingredients": [
      "Chana daal ¾ cup",
      "Mixed sabzi 1 cup",
      "Roti 1"
    ],
    "kcal": "~420",
    "protein": "~20",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Grilled chicken salad pita",
    "ingredients": [
      "Chicken breast 120 g",
      "Wholemeal pita ½",
      "Lettuce tomato onion",
      "Yoghurt mint dip 2 tbsp"
    ],
    "kcal": "~400",
    "protein": "~38",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Quinoa veg bowl",
    "ingredients": [
      "Cooked quinoa 150 g",
      "Roast veg 1 cup",
      "Chickpeas 80 g",
      "Lemon dressing 1 tsp oil"
    ],
    "kcal": "~420",
    "protein": "~18",
    "note": null,
    "source": "https://www.eatingwell.com/gallery/12279/our-best-quinoa-bowl-recipes/",
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Turkey or chicken lettuce wraps",
    "ingredients": [
      "Minced lean chicken 120 g",
      "Garlic ginger soy lite",
      "Lettuce cups 4",
      "Grated carrot"
    ],
    "kcal": "~350",
    "protein": "~36",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Tuna salad sandwich",
    "ingredients": [
      "Canned tuna in water 1 small can",
      "Low-fat yoghurt 2 tbsp instead of mayo",
      "Celery onion",
      "Bread 2 slices wholemeal"
    ],
    "kcal": "~380",
    "protein": "~32",
    "note": null,
    "source": "https://www.nhs.uk/live-well/eat-well/food-types/how-to-eat-more-fish/",
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Rajma (kidney bean curry) + small rice",
    "ingredients": [
      "Rajma ¾ cup cooked",
      "Tomato onion gravy",
      "Oil 1 tsp",
      "Rice 80 g cooked"
    ],
    "kcal": "~430",
    "protein": "~18",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Palak paneer (light) + roti",
    "ingredients": [
      "Paneer 70 g",
      "Spinach 2 cups pureed",
      "Milk 50 ml",
      "Roti 1"
    ],
    "kcal": "~420",
    "protein": "~24",
    "note": "Limit cream.",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Chicken tikka pieces + salad",
    "ingredients": [
      "Chicken 120 g tikka cubes",
      "Onion rings, lemon",
      "Mint chutney 1 tbsp"
    ],
    "kcal": "~380",
    "protein": "~40",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Fish curry + rice (weekly)",
    "ingredients": [
      "White fish 120 g",
      "Tomato coconut-lite gravy",
      "Rice 100 g"
    ],
    "kcal": "~420",
    "protein": "~34",
    "note": "Optional fish from dietitian list.",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Mixed veg pulao (oil controlled)",
    "ingredients": [
      "Basmati rice 90 g dry → cooked",
      "Mixed veg 1.5 cups",
      "Oil 1.5 tsp",
      "Spices"
    ],
    "kcal": "~400",
    "protein": "~9",
    "note": "Add yoghurt side for protein.",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Chickpea spinach stew",
    "ingredients": [
      "Chickpeas 150 g",
      "Spinach 2 cups",
      "Tomato base",
      "Cumin",
      "1 roti"
    ],
    "kcal": "~440",
    "protein": "~20",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Lentil soup + wholemeal roll",
    "ingredients": [
      "Red lentils 60 g dry",
      "Carrot celery",
      "Vegetable stock",
      "Small roll 40 g"
    ],
    "kcal": "~380",
    "protein": "~20",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Chicken shawarma bowl (homemade)",
    "ingredients": [
      "Chicken 120 g strips",
      "Cumin paprika marinade",
      "Brown rice 100 g",
      "Salad, toum replaced by yoghurt garlic"
    ],
    "kcal": "~450",
    "protein": "~40",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Egg fried rice (cauliflower half swap)",
    "ingredients": [
      "Cauliflower rice 150 g + rice 50 g cooked",
      "Eggs 2",
      "Peas carrot",
      "Soy sauce 1 tsp",
      "Oil 1 tsp"
    ],
    "kcal": "~400",
    "protein": "~26",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Stuffed bell pepper (quinoa)",
    "ingredients": [
      "Pepper 1 large",
      "Quinoa + turkey mince 100 g mix",
      "Tomato sauce no sugar"
    ],
    "kcal": "~400",
    "protein": "~32",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Mediterranean chickpea salad",
    "ingredients": [
      "Chickpeas 150 g",
      "Cucumber tomato parsley",
      "Feta 20 g",
      "Olive oil 1 tsp",
      "Lemon"
    ],
    "kcal": "~410",
    "protein": "~18",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Chicken noodle soup (veg noodles)",
    "ingredients": [
      "Chicken breast 100 g shredded",
      "Vegetable soup base",
      "Wholewheat noodles 40 g dry"
    ],
    "kcal": "~360",
    "protein": "~34",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Aloo gobi (dry) + daal + roti",
    "ingredients": [
      "Potato cauliflower dry sabzi 1 cup",
      "Daal ½ cup",
      "Roti 1"
    ],
    "kcal": "~400",
    "protein": "~14",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Soba + edamame sesame",
    "ingredients": [
      "Soba noodles 50 g dry",
      "Edamame 80 g",
      "Sesame 1 tsp",
      "Soy ginger dressing"
    ],
    "kcal": "~380",
    "protein": "~20",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Chicken Caesar salad (yoghurt dressing)",
    "ingredients": [
      "Chicken 120 g",
      "Romaine 2 cups",
      "Parmesan 10 g",
      "Yoghurt lemon garlic dressing"
    ],
    "kcal": "~380",
    "protein": "~40",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Falafel bowl (baked)",
    "ingredients": [
      "Baked falafels 3 small",
      "Hummus 2 tbsp",
      "Salad",
      "Pickle"
    ],
    "kcal": "~420",
    "protein": "~16",
    "note": "Bake instead of fry.",
    "source": null,
    "fromData": null
  },
  {
    "category": "lunch",
    "title": "Thai basil chicken (light)",
    "ingredients": [
      "Chicken mince 120 g",
      "Thai basil handful",
      "Chilli garlic",
      "Jasmine rice 100 g"
    ],
    "kcal": "~450",
    "protein": "~36",
    "note": "Use minimal oil.",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Low-cal chicken steak (dietitian style)",
    "ingredients": [
      "Chicken breast steaks 200–250 g total (4 thin pieces meal-prep)",
      "Olive oil 2 tbsp total marinade",
      "Garlic powder 1 tsp",
      "Paprika 1 tsp",
      "Salt 1 tsp",
      "Black pepper ½ tsp",
      "Cayenne ¼ tsp optional",
      "Parsley or thyme garnish"
    ],
    "kcal": "~260",
    "protein": "~40",
    "note": "Per 1 steak serving from photo notes; split batch.",
    "source": null,
    "fromData": "Macros & ingredients from your data/PHOTO chicken steak images"
  },
  {
    "category": "dinner",
    "title": "Wholemeal pasta + lean beef sauce",
    "ingredients": [
      "Wholewheat pasta 70 g dry",
      "Lean mince 100 g",
      "Tomato tin, onion garlic",
      "Italian herbs"
    ],
    "kcal": "~480",
    "protein": "~34",
    "note": "Dinner list: Pasta — from dietitian sheet.",
    "source": "https://www.bbcgoodfood.com/recipes/collection/healthy-pasta-recipes",
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Chicken tomato soup",
    "ingredients": [
      "Chicken breast 150 g",
      "Tinned tomatoes 400 g",
      "Onion carrot celery",
      "Stock",
      "Herbs"
    ],
    "kcal": "~320",
    "protein": "~38",
    "note": "Dietitian dinner list item.",
    "source": null,
    "fromData": "From dietitian photo dinner list"
  },
  {
    "category": "dinner",
    "title": "Steamed chicken + greens",
    "ingredients": [
      "Chicken breast 150 g",
      "Ginger spring onion steam",
      "Broccoli + beans 2 cups",
      "Soy 1 tsp + sesame drops"
    ],
    "kcal": "~350",
    "protein": "~45",
    "note": "Minimal oil steam.",
    "source": null,
    "fromData": "Dietitian: Steam chicken"
  },
  {
    "category": "dinner",
    "title": "Chicken curry + steamed veg",
    "ingredients": [
      "Chicken thigh trimmed 120 g",
      "Onion tomato gravy 1 tsp oil",
      "Steamed carrots + beans 1.5 cups"
    ],
    "kcal": "~430",
    "protein": "~35",
    "note": "Curry oil controlled.",
    "source": null,
    "fromData": "Dietitian dinner list"
  },
  {
    "category": "dinner",
    "title": "Pasta salad (protein)",
    "ingredients": [
      "Wholewheat pasta 60 g dry",
      "Chicken 100 g or chickpeas",
      "Cherry tomato cucumber",
      "Yoghurt herb dressing"
    ],
    "kcal": "~420",
    "protein": "~32",
    "note": null,
    "source": "https://www.eatingwell.com/healthy-pasta-salad-recipes-7095526",
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Steam fish with ginger (optional)",
    "ingredients": [
      "White fish fillet 150 g",
      "Ginger soy steam",
      "Pak choi 1 cup"
    ],
    "kcal": "~320",
    "protein": "~34",
    "note": "Optional fish note from sheet.",
    "source": null,
    "fromData": "Dietitian: Steam fish optional"
  },
  {
    "category": "dinner",
    "title": "Masala chicken + salad + roti",
    "ingredients": [
      "Chicken thigh 120 g",
      "Yoghurt marinade",
      "Salad",
      "Roti 1",
      "Oil 1 tsp cook"
    ],
    "kcal": "~430",
    "protein": "~38",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Turkey meatballs + zucchini noodles",
    "ingredients": [
      "Turkey mince 120 g",
      "Zucchini spirals 2 cups",
      "Marinara 150 g"
    ],
    "kcal": "~380",
    "protein": "~38",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Eggplant + daal + roti",
    "ingredients": [
      "Roast baingan mash",
      "Toor daal ½ cup",
      "Roti 1"
    ],
    "kcal": "~400",
    "protein": "~16",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Chicken seekh (oven) + raita",
    "ingredients": [
      "Seekh mix lean chicken 150 g",
      "Onion mint",
      "Raita 100 g"
    ],
    "kcal": "~420",
    "protein": "~36",
    "note": "Bake skewers.",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Stuffed zucchini (mince)",
    "ingredients": [
      "Zucchini boats",
      "Chicken mince 100 g",
      "Tomato topping",
      "Cheese 15 g"
    ],
    "kcal": "~380",
    "protein": "~36",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Keema matar (lean) + roti",
    "ingredients": [
      "Lean mince 120 g",
      "Peas ½ cup",
      "Tomato onion",
      "Roti 1"
    ],
    "kcal": "~450",
    "protein": "~32",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Grilled salmon + sweet potato",
    "ingredients": [
      "Salmon 120 g",
      "Sweet potato 150 g roast",
      "Green beans"
    ],
    "kcal": "~480",
    "protein": "~34",
    "note": "Omega-3 boost meal.",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Chicken tortilla soup",
    "ingredients": [
      "Chicken 120 g",
      "Black beans 80 g",
      "Tomato broth",
      "Tortilla strip 20 g baked"
    ],
    "kcal": "~400",
    "protein": "~36",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Bhindi masala dry + daal + roti",
    "ingredients": [
      "Okra dry 1 cup",
      "Masoor daal ½ cup",
      "Roti 1"
    ],
    "kcal": "~400",
    "protein": "~15",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Prawn garlic stir-fry + rice",
    "ingredients": [
      "Prawns 130 g",
      "Garlic ginger",
      "Veg mix",
      "Rice 90 g cooked"
    ],
    "kcal": "~430",
    "protein": "~34",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Stuffed tomato (quinoa paneer)",
    "ingredients": [
      "Large tomato 2 hollowed",
      "Paneer 50 g + quinoa filling",
      "Bake"
    ],
    "kcal": "~360",
    "protein": "~22",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Chicken pho-style broth bowl",
    "ingredients": [
      "Chicken breast 120 g",
      "Rice noodles 40 g dry",
      "Broth spices star anise lite",
      "Bean sprouts herbs"
    ],
    "kcal": "~400",
    "protein": "~36",
    "note": "Keep noodles modest.",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Mushroom stroganoff (yoghurt)",
    "ingredients": [
      "Mushrooms 200 g",
      "Chicken strips 80 g optional",
      "Yoghurt paprika sauce",
      "Wholewheat pasta 55 g dry"
    ],
    "kcal": "~440",
    "protein": "~30",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Sarson saag + makki roti small + daal",
    "ingredients": [
      "Saag 1 cup",
      "Makki roti 1 small or wheat 1",
      "Maash daal ¼ cup"
    ],
    "kcal": "~430",
    "protein": "~16",
    "note": "Portion control roti.",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Chicken chilli dry (minimal oil)",
    "ingredients": [
      "Chicken 150 g strips",
      "Capsicum onion",
      "Soy vinegar",
      "Oil 1.5 tsp"
    ],
    "kcal": "~400",
    "protein": "~40",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Greek chicken tray bake",
    "ingredients": [
      "Chicken thigh skinless 130 g",
      "Potato 120 g",
      "Peppers onion",
      "Oregano lemon"
    ],
    "kcal": "~460",
    "protein": "~38",
    "note": "One tray easy.",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Tofu stir-fry + brown rice",
    "ingredients": [
      "Firm tofu 150 g",
      "Mixed veg",
      "Ginger garlic",
      "Brown rice 100 g cooked"
    ],
    "kcal": "~420",
    "protein": "~22",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Channa palak + roti",
    "ingredients": [
      "Kabuli chana 120 g",
      "Spinach gravy",
      "Roti 1"
    ],
    "kcal": "~430",
    "protein": "~18",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Baked pesto chicken + veg",
    "ingredients": [
      "Chicken 150 g",
      "Pesto 1 tbsp",
      "Tray veg 2 cups"
    ],
    "kcal": "~430",
    "protein": "~42",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Veg kofta yoghurt gravy + roti",
    "ingredients": [
      "Bottle gourd kofta baked 3",
      "Yoghurt cashew-light gravy",
      "Roti 1"
    ],
    "kcal": "~400",
    "protein": "~12",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "dinner",
    "title": "Harissa chicken + couscous",
    "ingredients": [
      "Chicken 130 g",
      "Harissa 1 tsp paste",
      "Wholewheat couscous 50 g dry",
      "Salad"
    ],
    "kcal": "~450",
    "protein": "~40",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "snack",
    "title": "Protein yoghurt cup",
    "ingredients": [
      "Yoghurt 150 g",
      "Chia 1 tsp",
      "Berries"
    ],
    "kcal": "~180",
    "protein": "~15",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "snack",
    "title": "Apple + almonds",
    "ingredients": [
      "Apple 1",
      "Almonds 10"
    ],
    "kcal": "~160",
    "protein": "~5",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "snack",
    "title": "Cottage cheese + tomatoes",
    "ingredients": [
      "Cottage cheese 100 g",
      "Cherry tomatoes"
    ],
    "kcal": "~140",
    "protein": "~18",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "snack",
    "title": "Hummus + carrot",
    "ingredients": [
      "Hummus 40 g",
      "Carrot sticks 150 g"
    ],
    "kcal": "~180",
    "protein": "~8",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "snack",
    "title": "Boiled egg + cucumber",
    "ingredients": [
      "Egg 1",
      "Cucumber"
    ],
    "kcal": "~120",
    "protein": "~12",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "snack",
    "title": "Roasted chana handful",
    "ingredients": [
      "Dry roasted chana 30 g"
    ],
    "kcal": "~130",
    "protein": "~8",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "snack",
    "title": "Protein shake (powder)",
    "ingredients": [
      "Water or milk 250 ml",
      "Whey scoop 25 g"
    ],
    "kcal": "~180",
    "protein": "~22",
    "note": "If supplementing.",
    "source": null,
    "fromData": null
  },
  {
    "category": "snack",
    "title": "Rice cake + peanut butter",
    "ingredients": [
      "Rice cake 2",
      "Peanut butter 1 tsp each thin"
    ],
    "kcal": "~180",
    "protein": "~7",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "snack",
    "title": "Dates + walnuts",
    "ingredients": [
      "Dates 2",
      "Walnut halves 3"
    ],
    "kcal": "~150",
    "protein": "~3",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "snack",
    "title": "Edamame pods salted light",
    "ingredients": [
      "Edamame 100 g pods"
    ],
    "kcal": "~120",
    "protein": "~12",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "snack",
    "title": "Caprese skewer",
    "ingredients": [
      "Mozzarella light 40 g",
      "Tomato basil",
      "Balsamic spray"
    ],
    "kcal": "~120",
    "protein": "~12",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "snack",
    "title": "Popcorn air-popped",
    "ingredients": [
      "Corn kernels 15 g unpopped"
    ],
    "kcal": "~120",
    "protein": "~3",
    "note": "No butter.",
    "source": null,
    "fromData": null
  },
  {
    "category": "snack",
    "title": "Tuna on cucumber rounds",
    "ingredients": [
      "Tuna 60 g",
      "Cucumber slices"
    ],
    "kcal": "~120",
    "protein": "~16",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "snack",
    "title": "Sliced chicken roll-ups",
    "ingredients": [
      "Chicken slices 80 g",
      "Lettuce mustard"
    ],
    "kcal": "~140",
    "protein": "~22",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "snack",
    "title": "Fruit chaat (no syrup)",
    "ingredients": [
      "Mixed fruit 200 g",
      "Lemon chaat masala"
    ],
    "kcal": "~120",
    "protein": "~2",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "snack",
    "title": "Roasted makhana 25 g",
    "ingredients": [
      "Foxnuts 25 g",
      "Spices dry"
    ],
    "kcal": "~90",
    "protein": "~3",
    "note": "",
    "source": null,
    "fromData": null
  },
  {
    "category": "drink",
    "title": "Cinnamon green tea + ACV + honey (anti-inflammatory)",
    "ingredients": [
      "Water",
      "Cinnamon stick 1",
      "Green tea bag or leaves",
      "Apple cider vinegar 1 tbsp after cooling",
      "Honey 1 tsp"
    ],
    "kcal": "~40",
    "protein": "~0",
    "note": "Boil water with cinnamon 5 min; steep green tea 2–3 min; strain; cool slightly; stir ACV + honey. Drink before last meal.",
    "source": null,
    "fromData": "Steps from data/PHOTO-2025-12-15-14-45-45 2.jpg"
  },
  {
    "category": "drink",
    "title": "Golden milk (turmeric latte)",
    "ingredients": [
      "Semi-skimmed milk 200 ml",
      "Turmeric ½ tsp",
      "Black pepper pinch",
      "Cinnamon pinch",
      "Sweetener small"
    ],
    "kcal": "~120",
    "protein": "~8",
    "note": "Warm; anti-inflammatory spices.",
    "source": null,
    "fromData": null
  },
  {
    "category": "drink",
    "title": "Ginger lemon warm water",
    "ingredients": [
      "Water 250 ml",
      "Ginger slices",
      "Lemon ½",
      "Optional honey ½ tsp"
    ],
    "kcal": "~25",
    "protein": "~0",
    "note": "Morning hydration.",
    "source": null,
    "fromData": null
  },
  {
    "category": "drink",
    "title": "Green juice (cucumber celery spinach)",
    "ingredients": [
      "Cucumber ½",
      "Celery stalk 1",
      "Spinach handful",
      "Lemon squeeze"
    ],
    "kcal": "~50",
    "protein": "~2",
    "note": "Cold-press or blitz + strain.",
    "source": null,
    "fromData": null
  },
  {
    "category": "drink",
    "title": "Mint cucumber cooler",
    "ingredients": [
      "Cucumber 100 g",
      "Mint leaves",
      "Water",
      "Lime",
      "Salt pinch"
    ],
    "kcal": "~20",
    "protein": "~1",
    "note": "No sugar soda alternative.",
    "source": null,
    "fromData": null
  },
  {
    "category": "drink",
    "title": "Rose hibiscus tea (no sugar)",
    "ingredients": [
      "Dried hibiscus",
      "Water",
      "Rose water drop"
    ],
    "kcal": "~5",
    "protein": "~0",
    "note": "Steep 5 min.",
    "source": null,
    "fromData": null
  },
  {
    "category": "drink",
    "title": "Berry kefir smoothie",
    "ingredients": [
      "Kefir or yoghurt 200 ml",
      "Mixed berries 80 g",
      "Flax 1 tsp ground"
    ],
    "kcal": "~200",
    "protein": "~12",
    "note": "Gut-friendly option.",
    "source": null,
    "fromData": null
  },
  {
    "category": "drink",
    "title": "Tart cherry + water",
    "ingredients": [
      "Tart cherry concentrate 1 tbsp",
      "Water 300 ml"
    ],
    "kcal": "~80",
    "protein": "~0",
    "note": "Recovery drink some athletes use.",
    "source": null,
    "fromData": null
  },
  {
    "category": "drink",
    "title": "Tulsi ginger tea",
    "ingredients": [
      "Holy basil tea bag",
      "Ginger",
      "Hot water"
    ],
    "kcal": "~5",
    "protein": "~0",
    "note": "Herbal calm.",
    "source": null,
    "fromData": null
  },
  {
    "category": "drink",
    "title": "Moringa lemon water",
    "ingredients": [
      "Moringa powder ½ tsp",
      "Water",
      "Lemon"
    ],
    "kcal": "~15",
    "protein": "~1",
    "note": "Trend greens — watch sourcing.",
    "source": null,
    "fromData": null
  }
];
